version: '3.9'

services:
  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
